// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: liga/liga.proto

package liga

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// liga
type AllLigaRequest struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllLigaRequest) Reset()         { *m = AllLigaRequest{} }
func (m *AllLigaRequest) String() string { return proto.CompactTextString(m) }
func (*AllLigaRequest) ProtoMessage()    {}
func (*AllLigaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1f8d8504eb0d8c, []int{0}
}
func (m *AllLigaRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AllLigaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AllLigaRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AllLigaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllLigaRequest.Merge(m, src)
}
func (m *AllLigaRequest) XXX_Size() int {
	return m.Size()
}
func (m *AllLigaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllLigaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllLigaRequest proto.InternalMessageInfo

func (m *AllLigaRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AllLigaRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Ligas struct {
	Ligas                []*LigaResponse `protobuf:"bytes,1,rep,name=ligas,proto3" json:"ligas"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Ligas) Reset()         { *m = Ligas{} }
func (m *Ligas) String() string { return proto.CompactTextString(m) }
func (*Ligas) ProtoMessage()    {}
func (*Ligas) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1f8d8504eb0d8c, []int{1}
}
func (m *Ligas) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ligas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ligas.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Ligas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ligas.Merge(m, src)
}
func (m *Ligas) XXX_Size() int {
	return m.Size()
}
func (m *Ligas) XXX_DiscardUnknown() {
	xxx_messageInfo_Ligas.DiscardUnknown(m)
}

var xxx_messageInfo_Ligas proto.InternalMessageInfo

func (m *Ligas) GetLigas() []*LigaResponse {
	if m != nil {
		return m.Ligas
	}
	return nil
}

type LigaResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LigaResponse) Reset()         { *m = LigaResponse{} }
func (m *LigaResponse) String() string { return proto.CompactTextString(m) }
func (*LigaResponse) ProtoMessage()    {}
func (*LigaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1f8d8504eb0d8c, []int{2}
}
func (m *LigaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LigaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LigaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LigaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LigaResponse.Merge(m, src)
}
func (m *LigaResponse) XXX_Size() int {
	return m.Size()
}
func (m *LigaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LigaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LigaResponse proto.InternalMessageInfo

func (m *LigaResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LigaResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LigaResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *LigaResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type LigaRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LigaRequest) Reset()         { *m = LigaRequest{} }
func (m *LigaRequest) String() string { return proto.CompactTextString(m) }
func (*LigaRequest) ProtoMessage()    {}
func (*LigaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1f8d8504eb0d8c, []int{3}
}
func (m *LigaRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LigaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LigaRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LigaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LigaRequest.Merge(m, src)
}
func (m *LigaRequest) XXX_Size() int {
	return m.Size()
}
func (m *LigaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LigaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LigaRequest proto.InternalMessageInfo

func (m *LigaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type IdRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1f8d8504eb0d8c, []int{4}
}
func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return m.Size()
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Game
type AllGameRequest struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllGameRequest) Reset()         { *m = AllGameRequest{} }
func (m *AllGameRequest) String() string { return proto.CompactTextString(m) }
func (*AllGameRequest) ProtoMessage()    {}
func (*AllGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1f8d8504eb0d8c, []int{5}
}
func (m *AllGameRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AllGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AllGameRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AllGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllGameRequest.Merge(m, src)
}
func (m *AllGameRequest) XXX_Size() int {
	return m.Size()
}
func (m *AllGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllGameRequest proto.InternalMessageInfo

func (m *AllGameRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AllGameRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Games struct {
	Games                []*GameResponse `protobuf:"bytes,1,rep,name=Games,proto3" json:"Games"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Games) Reset()         { *m = Games{} }
func (m *Games) String() string { return proto.CompactTextString(m) }
func (*Games) ProtoMessage()    {}
func (*Games) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1f8d8504eb0d8c, []int{6}
}
func (m *Games) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Games) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Games.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Games) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Games.Merge(m, src)
}
func (m *Games) XXX_Size() int {
	return m.Size()
}
func (m *Games) XXX_DiscardUnknown() {
	xxx_messageInfo_Games.DiscardUnknown(m)
}

var xxx_messageInfo_Games proto.InternalMessageInfo

func (m *Games) GetGames() []*GameResponse {
	if m != nil {
		return m.Games
	}
	return nil
}

type GameResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time"`
	Condtion             bool     `protobuf:"varint,3,opt,name=condtion,proto3" json:"condtion"`
	FirstTeamId          int64    `protobuf:"varint,4,opt,name=first_team_id,json=firstTeamId,proto3" json:"first_team_id"`
	SecondTeamId         int64    `protobuf:"varint,5,opt,name=second_team_id,json=secondTeamId,proto3" json:"second_team_id"`
	ResultFirstTeam      int64    `protobuf:"varint,6,opt,name=result_first_team,json=resultFirstTeam,proto3" json:"result_first_team"`
	ResultSecondTeam     int64    `protobuf:"varint,7,opt,name=result_second_team,json=resultSecondTeam,proto3" json:"result_second_team"`
	FirstTeamPoint       int64    `protobuf:"varint,8,opt,name=first_team_point,json=firstTeamPoint,proto3" json:"first_team_point"`
	SecondTeamPoint      int64    `protobuf:"varint,9,opt,name=second_team_point,json=secondTeamPoint,proto3" json:"second_team_point"`
	LigaId               int64    `protobuf:"varint,10,opt,name=liga_id,json=ligaId,proto3" json:"liga_id"`
	CreatedAt            string   `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt            string   `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameResponse) Reset()         { *m = GameResponse{} }
func (m *GameResponse) String() string { return proto.CompactTextString(m) }
func (*GameResponse) ProtoMessage()    {}
func (*GameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1f8d8504eb0d8c, []int{7}
}
func (m *GameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResponse.Merge(m, src)
}
func (m *GameResponse) XXX_Size() int {
	return m.Size()
}
func (m *GameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameResponse proto.InternalMessageInfo

func (m *GameResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GameResponse) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *GameResponse) GetCondtion() bool {
	if m != nil {
		return m.Condtion
	}
	return false
}

func (m *GameResponse) GetFirstTeamId() int64 {
	if m != nil {
		return m.FirstTeamId
	}
	return 0
}

func (m *GameResponse) GetSecondTeamId() int64 {
	if m != nil {
		return m.SecondTeamId
	}
	return 0
}

func (m *GameResponse) GetResultFirstTeam() int64 {
	if m != nil {
		return m.ResultFirstTeam
	}
	return 0
}

func (m *GameResponse) GetResultSecondTeam() int64 {
	if m != nil {
		return m.ResultSecondTeam
	}
	return 0
}

func (m *GameResponse) GetFirstTeamPoint() int64 {
	if m != nil {
		return m.FirstTeamPoint
	}
	return 0
}

func (m *GameResponse) GetSecondTeamPoint() int64 {
	if m != nil {
		return m.SecondTeamPoint
	}
	return 0
}

func (m *GameResponse) GetLigaId() int64 {
	if m != nil {
		return m.LigaId
	}
	return 0
}

func (m *GameResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GameResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GameRequest struct {
	Time                 string   `protobuf:"bytes,1,opt,name=time,proto3" json:"time"`
	Condtion             bool     `protobuf:"varint,2,opt,name=condtion,proto3" json:"condtion"`
	FirstTeamId          int64    `protobuf:"varint,3,opt,name=first_team_id,json=firstTeamId,proto3" json:"first_team_id"`
	SecondTeamId         int64    `protobuf:"varint,4,opt,name=second_team_id,json=secondTeamId,proto3" json:"second_team_id"`
	ResultFirstTeam      int64    `protobuf:"varint,5,opt,name=result_first_team,json=resultFirstTeam,proto3" json:"result_first_team"`
	ResultSecondTeam     int64    `protobuf:"varint,6,opt,name=result_second_team,json=resultSecondTeam,proto3" json:"result_second_team"`
	FirstTeamPoint       int64    `protobuf:"varint,7,opt,name=first_team_point,json=firstTeamPoint,proto3" json:"first_team_point"`
	SecondTeamPoint      int64    `protobuf:"varint,8,opt,name=second_team_point,json=secondTeamPoint,proto3" json:"second_team_point"`
	LigaId               int64    `protobuf:"varint,9,opt,name=liga_id,json=ligaId,proto3" json:"liga_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameRequest) Reset()         { *m = GameRequest{} }
func (m *GameRequest) String() string { return proto.CompactTextString(m) }
func (*GameRequest) ProtoMessage()    {}
func (*GameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1f8d8504eb0d8c, []int{8}
}
func (m *GameRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GameRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameRequest.Merge(m, src)
}
func (m *GameRequest) XXX_Size() int {
	return m.Size()
}
func (m *GameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameRequest proto.InternalMessageInfo

func (m *GameRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *GameRequest) GetCondtion() bool {
	if m != nil {
		return m.Condtion
	}
	return false
}

func (m *GameRequest) GetFirstTeamId() int64 {
	if m != nil {
		return m.FirstTeamId
	}
	return 0
}

func (m *GameRequest) GetSecondTeamId() int64 {
	if m != nil {
		return m.SecondTeamId
	}
	return 0
}

func (m *GameRequest) GetResultFirstTeam() int64 {
	if m != nil {
		return m.ResultFirstTeam
	}
	return 0
}

func (m *GameRequest) GetResultSecondTeam() int64 {
	if m != nil {
		return m.ResultSecondTeam
	}
	return 0
}

func (m *GameRequest) GetFirstTeamPoint() int64 {
	if m != nil {
		return m.FirstTeamPoint
	}
	return 0
}

func (m *GameRequest) GetSecondTeamPoint() int64 {
	if m != nil {
		return m.SecondTeamPoint
	}
	return 0
}

func (m *GameRequest) GetLigaId() int64 {
	if m != nil {
		return m.LigaId
	}
	return 0
}

func init() {
	proto.RegisterType((*AllLigaRequest)(nil), "liga.AllLigaRequest")
	proto.RegisterType((*Ligas)(nil), "liga.Ligas")
	proto.RegisterType((*LigaResponse)(nil), "liga.LigaResponse")
	proto.RegisterType((*LigaRequest)(nil), "liga.LigaRequest")
	proto.RegisterType((*IdRequest)(nil), "liga.IdRequest")
	proto.RegisterType((*AllGameRequest)(nil), "liga.AllGameRequest")
	proto.RegisterType((*Games)(nil), "liga.Games")
	proto.RegisterType((*GameResponse)(nil), "liga.GameResponse")
	proto.RegisterType((*GameRequest)(nil), "liga.GameRequest")
}

func init() { proto.RegisterFile("liga/liga.proto", fileDescriptor_bf1f8d8504eb0d8c) }

var fileDescriptor_bf1f8d8504eb0d8c = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0xe3, 0xfc, 0x8e, 0x43, 0x92, 0x8e, 0x2a, 0x61, 0x05, 0x11, 0x05, 0x8b, 0x43, 0x84,
	0x50, 0x11, 0x29, 0x5c, 0xb8, 0xa5, 0x20, 0xaa, 0x48, 0x1c, 0x90, 0xcb, 0x3d, 0x32, 0xd9, 0x25,
	0x5a, 0xc9, 0x89, 0x4d, 0x76, 0x83, 0xc4, 0x9b, 0x70, 0xe3, 0x39, 0x78, 0x03, 0x8e, 0x7d, 0x04,
	0x14, 0x5e, 0x04, 0xed, 0xac, 0x63, 0x3b, 0x56, 0xda, 0xba, 0x5c, 0xa2, 0xdd, 0x6f, 0xbe, 0xd9,
	0xf9, 0xf9, 0xc6, 0x13, 0xe8, 0x85, 0x62, 0x19, 0xbc, 0xd0, 0x3f, 0x67, 0xf1, 0x26, 0x52, 0x11,
	0xd6, 0xf4, 0xd9, 0x7b, 0x03, 0xdd, 0x69, 0x18, 0x7e, 0x10, 0xcb, 0xc0, 0xe7, 0x5f, 0xb7, 0x5c,
	0x2a, 0x44, 0xa8, 0xc5, 0xc1, 0x92, 0xbb, 0xd6, 0xc8, 0x1a, 0xdb, 0x3e, 0x9d, 0xf1, 0x14, 0xea,
	0xa1, 0x58, 0x09, 0xe5, 0x56, 0x09, 0x34, 0x17, 0xef, 0x25, 0xd4, 0xb5, 0xa3, 0xc4, 0xb1, 0x36,
	0x2f, 0x03, 0xe9, 0x5a, 0x23, 0x7b, 0xec, 0x4c, 0xf0, 0x8c, 0xc2, 0x98, 0x47, 0x65, 0x1c, 0xad,
	0x25, 0xf7, 0x0d, 0xc1, 0x8b, 0xa1, 0x93, 0x87, 0xb1, 0x0b, 0x55, 0xc1, 0x92, 0x50, 0x55, 0xc1,
	0x74, 0xf0, 0x75, 0xb0, 0xe2, 0x14, 0xa7, 0xed, 0xd3, 0x19, 0x1f, 0x03, 0x2c, 0x36, 0x3c, 0x50,
	0x9c, 0xcd, 0x03, 0xe5, 0xd6, 0xc8, 0xd2, 0x4e, 0x90, 0xa9, 0xd2, 0xe6, 0x6d, 0xcc, 0xf6, 0xe6,
	0xba, 0x31, 0x27, 0xc8, 0x54, 0x79, 0x4f, 0xc0, 0x29, 0x54, 0x47, 0x01, 0xac, 0x2c, 0x80, 0xf7,
	0x08, 0xda, 0x33, 0xb6, 0x27, 0x14, 0x32, 0x4a, 0x1a, 0x74, 0x19, 0xac, 0xf8, 0x7f, 0x35, 0x48,
	0x3b, 0x52, 0x83, 0xe8, 0x70, 0xd8, 0x20, 0xf3, 0xe8, 0xbe, 0x41, 0x44, 0xf0, 0x7e, 0xda, 0xd0,
	0xc9, 0xe3, 0xc7, 0x3a, 0xa4, 0x44, 0xd6, 0x21, 0x7d, 0xc6, 0x01, 0xb4, 0x16, 0xd1, 0x9a, 0x29,
	0x11, 0xad, 0x5d, 0x7b, 0x64, 0x8d, 0x5b, 0x7e, 0x7a, 0x47, 0x0f, 0x1e, 0x7c, 0x11, 0x1b, 0xa9,
	0xe6, 0x8a, 0x07, 0xab, 0xb9, 0x60, 0xd4, 0x40, 0xdb, 0x77, 0x08, 0xfc, 0xc4, 0x83, 0xd5, 0x8c,
	0xe1, 0x53, 0xe8, 0x4a, 0xae, 0x3d, 0x52, 0x52, 0x9d, 0x48, 0x1d, 0x83, 0x26, 0xac, 0x67, 0x70,
	0xb2, 0xe1, 0x72, 0x1b, 0xaa, 0x79, 0xf6, 0xa0, 0xdb, 0x20, 0x62, 0xcf, 0x18, 0xde, 0xef, 0xdf,
	0xc4, 0xe7, 0x80, 0x09, 0x37, 0xf7, 0xb0, 0xdb, 0x24, 0x72, 0xdf, 0x58, 0xae, 0xd2, 0xb7, 0x71,
	0x0c, 0xfd, 0x5c, 0x8e, 0x71, 0x24, 0xd6, 0xca, 0x6d, 0x11, 0xb7, 0x9b, 0xa6, 0xf9, 0x51, 0xa3,
	0x3a, 0x87, 0x7c, 0xa6, 0x86, 0xda, 0x36, 0x39, 0x64, 0xc9, 0x1a, 0xee, 0x43, 0x68, 0xea, 0x36,
	0xeb, 0x72, 0x80, 0x18, 0x0d, 0x7d, 0x9d, 0xb1, 0xc2, 0x40, 0x39, 0xb7, 0x0f, 0x54, 0xa7, 0x38,
	0x50, 0xd7, 0x55, 0x70, 0x0a, 0xe3, 0x40, 0x82, 0x58, 0x37, 0x08, 0x52, 0xbd, 0x4b, 0x10, 0xbb,
	0x8c, 0x20, 0xb5, 0xb2, 0x82, 0xd4, 0xef, 0x23, 0x48, 0xe3, 0x1e, 0x82, 0x34, 0xcb, 0x0b, 0xd2,
	0xba, 0x53, 0x90, 0x76, 0x5e, 0x90, 0xc9, 0x2f, 0xdb, 0x7c, 0xa4, 0x57, 0x7c, 0xf3, 0x4d, 0x2c,
	0x38, 0xbe, 0x06, 0x78, 0x4b, 0x72, 0x68, 0x10, 0x4f, 0xf2, 0xeb, 0x84, 0x7a, 0x3e, 0x38, 0xb2,
	0x61, 0xbc, 0x0a, 0xbe, 0x02, 0xe7, 0x92, 0x2b, 0x0d, 0x5e, 0x7c, 0x9f, 0x31, 0xec, 0x19, 0x52,
	0xfa, 0x69, 0xdf, 0xe0, 0x35, 0x21, 0xaf, 0x64, 0x09, 0x4a, 0x3c, 0x35, 0xa4, 0xc3, 0xa5, 0x38,
	0x70, 0x32, 0x57, 0xe9, 0x55, 0xf0, 0x1c, 0xe0, 0x1d, 0x0f, 0x79, 0x92, 0x60, 0xc9, 0x40, 0x69,
	0x55, 0x7a, 0x7a, 0xf6, 0x55, 0xe5, 0x26, 0x69, 0x70, 0x64, 0x2d, 0xa4, 0x55, 0x69, 0xf0, 0xd6,
	0xaa, 0x0a, 0x5e, 0x69, 0x55, 0x66, 0x01, 0x65, 0x55, 0xe5, 0x03, 0x3a, 0x99, 0xeb, 0x41, 0x55,
	0x94, 0x60, 0xb9, 0x40, 0x17, 0xfd, 0xdf, 0xbb, 0xa1, 0x75, 0xbd, 0x1b, 0x5a, 0x7f, 0x76, 0x43,
	0xeb, 0xc7, 0xdf, 0x61, 0xe5, 0x73, 0x83, 0xfe, 0x5f, 0xce, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xbf, 0x91, 0x88, 0x4b, 0x72, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LigaServiceClient is the client API for LigaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LigaServiceClient interface {
	// liga
	CreateLiga(ctx context.Context, in *LigaRequest, opts ...grpc.CallOption) (*LigaResponse, error)
	GetLigaById(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*LigaResponse, error)
	GetAllLigas(ctx context.Context, in *AllLigaRequest, opts ...grpc.CallOption) (*Ligas, error)
	DeleteLiga(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*LigaResponse, error)
	// game
	CreateGame(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*GameResponse, error)
	GetGameById(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*GameResponse, error)
	GetAllGames(ctx context.Context, in *AllGameRequest, opts ...grpc.CallOption) (*Games, error)
	DeleteGame(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*GameResponse, error)
}

type ligaServiceClient struct {
	cc *grpc.ClientConn
}

func NewLigaServiceClient(cc *grpc.ClientConn) LigaServiceClient {
	return &ligaServiceClient{cc}
}

func (c *ligaServiceClient) CreateLiga(ctx context.Context, in *LigaRequest, opts ...grpc.CallOption) (*LigaResponse, error) {
	out := new(LigaResponse)
	err := c.cc.Invoke(ctx, "/liga.LigaService/CreateLiga", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ligaServiceClient) GetLigaById(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*LigaResponse, error) {
	out := new(LigaResponse)
	err := c.cc.Invoke(ctx, "/liga.LigaService/GetLigaById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ligaServiceClient) GetAllLigas(ctx context.Context, in *AllLigaRequest, opts ...grpc.CallOption) (*Ligas, error) {
	out := new(Ligas)
	err := c.cc.Invoke(ctx, "/liga.LigaService/GetAllLigas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ligaServiceClient) DeleteLiga(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*LigaResponse, error) {
	out := new(LigaResponse)
	err := c.cc.Invoke(ctx, "/liga.LigaService/DeleteLiga", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ligaServiceClient) CreateGame(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*GameResponse, error) {
	out := new(GameResponse)
	err := c.cc.Invoke(ctx, "/liga.LigaService/CreateGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ligaServiceClient) GetGameById(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*GameResponse, error) {
	out := new(GameResponse)
	err := c.cc.Invoke(ctx, "/liga.LigaService/GetGameById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ligaServiceClient) GetAllGames(ctx context.Context, in *AllGameRequest, opts ...grpc.CallOption) (*Games, error) {
	out := new(Games)
	err := c.cc.Invoke(ctx, "/liga.LigaService/GetAllGames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ligaServiceClient) DeleteGame(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*GameResponse, error) {
	out := new(GameResponse)
	err := c.cc.Invoke(ctx, "/liga.LigaService/DeleteGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LigaServiceServer is the server API for LigaService service.
type LigaServiceServer interface {
	// liga
	CreateLiga(context.Context, *LigaRequest) (*LigaResponse, error)
	GetLigaById(context.Context, *IdRequest) (*LigaResponse, error)
	GetAllLigas(context.Context, *AllLigaRequest) (*Ligas, error)
	DeleteLiga(context.Context, *IdRequest) (*LigaResponse, error)
	// game
	CreateGame(context.Context, *GameRequest) (*GameResponse, error)
	GetGameById(context.Context, *IdRequest) (*GameResponse, error)
	GetAllGames(context.Context, *AllGameRequest) (*Games, error)
	DeleteGame(context.Context, *IdRequest) (*GameResponse, error)
}

// UnimplementedLigaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLigaServiceServer struct {
}

func (*UnimplementedLigaServiceServer) CreateLiga(ctx context.Context, req *LigaRequest) (*LigaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLiga not implemented")
}
func (*UnimplementedLigaServiceServer) GetLigaById(ctx context.Context, req *IdRequest) (*LigaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLigaById not implemented")
}
func (*UnimplementedLigaServiceServer) GetAllLigas(ctx context.Context, req *AllLigaRequest) (*Ligas, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllLigas not implemented")
}
func (*UnimplementedLigaServiceServer) DeleteLiga(ctx context.Context, req *IdRequest) (*LigaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLiga not implemented")
}
func (*UnimplementedLigaServiceServer) CreateGame(ctx context.Context, req *GameRequest) (*GameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (*UnimplementedLigaServiceServer) GetGameById(ctx context.Context, req *IdRequest) (*GameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameById not implemented")
}
func (*UnimplementedLigaServiceServer) GetAllGames(ctx context.Context, req *AllGameRequest) (*Games, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllGames not implemented")
}
func (*UnimplementedLigaServiceServer) DeleteGame(ctx context.Context, req *IdRequest) (*GameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGame not implemented")
}

func RegisterLigaServiceServer(s *grpc.Server, srv LigaServiceServer) {
	s.RegisterService(&_LigaService_serviceDesc, srv)
}

func _LigaService_CreateLiga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LigaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LigaServiceServer).CreateLiga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liga.LigaService/CreateLiga",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LigaServiceServer).CreateLiga(ctx, req.(*LigaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LigaService_GetLigaById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LigaServiceServer).GetLigaById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liga.LigaService/GetLigaById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LigaServiceServer).GetLigaById(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LigaService_GetAllLigas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllLigaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LigaServiceServer).GetAllLigas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liga.LigaService/GetAllLigas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LigaServiceServer).GetAllLigas(ctx, req.(*AllLigaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LigaService_DeleteLiga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LigaServiceServer).DeleteLiga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liga.LigaService/DeleteLiga",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LigaServiceServer).DeleteLiga(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LigaService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LigaServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liga.LigaService/CreateGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LigaServiceServer).CreateGame(ctx, req.(*GameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LigaService_GetGameById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LigaServiceServer).GetGameById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liga.LigaService/GetGameById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LigaServiceServer).GetGameById(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LigaService_GetAllGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LigaServiceServer).GetAllGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liga.LigaService/GetAllGames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LigaServiceServer).GetAllGames(ctx, req.(*AllGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LigaService_DeleteGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LigaServiceServer).DeleteGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liga.LigaService/DeleteGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LigaServiceServer).DeleteGame(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LigaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "liga.LigaService",
	HandlerType: (*LigaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLiga",
			Handler:    _LigaService_CreateLiga_Handler,
		},
		{
			MethodName: "GetLigaById",
			Handler:    _LigaService_GetLigaById_Handler,
		},
		{
			MethodName: "GetAllLigas",
			Handler:    _LigaService_GetAllLigas_Handler,
		},
		{
			MethodName: "DeleteLiga",
			Handler:    _LigaService_DeleteLiga_Handler,
		},
		{
			MethodName: "CreateGame",
			Handler:    _LigaService_CreateGame_Handler,
		},
		{
			MethodName: "GetGameById",
			Handler:    _LigaService_GetGameById_Handler,
		},
		{
			MethodName: "GetAllGames",
			Handler:    _LigaService_GetAllGames_Handler,
		},
		{
			MethodName: "DeleteGame",
			Handler:    _LigaService_DeleteGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "liga/liga.proto",
}

func (m *AllLigaRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AllLigaRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllLigaRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Limit != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x10
	}
	if m.Page != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.Page))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Ligas) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ligas) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Ligas) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Ligas) > 0 {
		for iNdEx := len(m.Ligas) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Ligas[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLiga(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *LigaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LigaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LigaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.UpdatedAt) > 0 {
		i -= len(m.UpdatedAt)
		copy(dAtA[i:], m.UpdatedAt)
		i = encodeVarintLiga(dAtA, i, uint64(len(m.UpdatedAt)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CreatedAt) > 0 {
		i -= len(m.CreatedAt)
		copy(dAtA[i:], m.CreatedAt)
		i = encodeVarintLiga(dAtA, i, uint64(len(m.CreatedAt)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintLiga(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LigaRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LigaRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LigaRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintLiga(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *IdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Id != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AllGameRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AllGameRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllGameRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Limit != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x10
	}
	if m.Page != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.Page))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Games) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Games) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Games) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Games) > 0 {
		for iNdEx := len(m.Games) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Games[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLiga(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.UpdatedAt) > 0 {
		i -= len(m.UpdatedAt)
		copy(dAtA[i:], m.UpdatedAt)
		i = encodeVarintLiga(dAtA, i, uint64(len(m.UpdatedAt)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.CreatedAt) > 0 {
		i -= len(m.CreatedAt)
		copy(dAtA[i:], m.CreatedAt)
		i = encodeVarintLiga(dAtA, i, uint64(len(m.CreatedAt)))
		i--
		dAtA[i] = 0x5a
	}
	if m.LigaId != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.LigaId))
		i--
		dAtA[i] = 0x50
	}
	if m.SecondTeamPoint != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.SecondTeamPoint))
		i--
		dAtA[i] = 0x48
	}
	if m.FirstTeamPoint != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.FirstTeamPoint))
		i--
		dAtA[i] = 0x40
	}
	if m.ResultSecondTeam != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.ResultSecondTeam))
		i--
		dAtA[i] = 0x38
	}
	if m.ResultFirstTeam != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.ResultFirstTeam))
		i--
		dAtA[i] = 0x30
	}
	if m.SecondTeamId != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.SecondTeamId))
		i--
		dAtA[i] = 0x28
	}
	if m.FirstTeamId != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.FirstTeamId))
		i--
		dAtA[i] = 0x20
	}
	if m.Condtion {
		i--
		if m.Condtion {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Time) > 0 {
		i -= len(m.Time)
		copy(dAtA[i:], m.Time)
		i = encodeVarintLiga(dAtA, i, uint64(len(m.Time)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GameRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GameRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GameRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.LigaId != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.LigaId))
		i--
		dAtA[i] = 0x48
	}
	if m.SecondTeamPoint != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.SecondTeamPoint))
		i--
		dAtA[i] = 0x40
	}
	if m.FirstTeamPoint != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.FirstTeamPoint))
		i--
		dAtA[i] = 0x38
	}
	if m.ResultSecondTeam != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.ResultSecondTeam))
		i--
		dAtA[i] = 0x30
	}
	if m.ResultFirstTeam != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.ResultFirstTeam))
		i--
		dAtA[i] = 0x28
	}
	if m.SecondTeamId != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.SecondTeamId))
		i--
		dAtA[i] = 0x20
	}
	if m.FirstTeamId != 0 {
		i = encodeVarintLiga(dAtA, i, uint64(m.FirstTeamId))
		i--
		dAtA[i] = 0x18
	}
	if m.Condtion {
		i--
		if m.Condtion {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Time) > 0 {
		i -= len(m.Time)
		copy(dAtA[i:], m.Time)
		i = encodeVarintLiga(dAtA, i, uint64(len(m.Time)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLiga(dAtA []byte, offset int, v uint64) int {
	offset -= sovLiga(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AllLigaRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Page != 0 {
		n += 1 + sovLiga(uint64(m.Page))
	}
	if m.Limit != 0 {
		n += 1 + sovLiga(uint64(m.Limit))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Ligas) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ligas) > 0 {
		for _, e := range m.Ligas {
			l = e.Size()
			n += 1 + l + sovLiga(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *LigaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovLiga(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovLiga(uint64(l))
	}
	l = len(m.CreatedAt)
	if l > 0 {
		n += 1 + l + sovLiga(uint64(l))
	}
	l = len(m.UpdatedAt)
	if l > 0 {
		n += 1 + l + sovLiga(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *LigaRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovLiga(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *IdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovLiga(uint64(m.Id))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AllGameRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Page != 0 {
		n += 1 + sovLiga(uint64(m.Page))
	}
	if m.Limit != 0 {
		n += 1 + sovLiga(uint64(m.Limit))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Games) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Games) > 0 {
		for _, e := range m.Games {
			l = e.Size()
			n += 1 + l + sovLiga(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovLiga(uint64(m.Id))
	}
	l = len(m.Time)
	if l > 0 {
		n += 1 + l + sovLiga(uint64(l))
	}
	if m.Condtion {
		n += 2
	}
	if m.FirstTeamId != 0 {
		n += 1 + sovLiga(uint64(m.FirstTeamId))
	}
	if m.SecondTeamId != 0 {
		n += 1 + sovLiga(uint64(m.SecondTeamId))
	}
	if m.ResultFirstTeam != 0 {
		n += 1 + sovLiga(uint64(m.ResultFirstTeam))
	}
	if m.ResultSecondTeam != 0 {
		n += 1 + sovLiga(uint64(m.ResultSecondTeam))
	}
	if m.FirstTeamPoint != 0 {
		n += 1 + sovLiga(uint64(m.FirstTeamPoint))
	}
	if m.SecondTeamPoint != 0 {
		n += 1 + sovLiga(uint64(m.SecondTeamPoint))
	}
	if m.LigaId != 0 {
		n += 1 + sovLiga(uint64(m.LigaId))
	}
	l = len(m.CreatedAt)
	if l > 0 {
		n += 1 + l + sovLiga(uint64(l))
	}
	l = len(m.UpdatedAt)
	if l > 0 {
		n += 1 + l + sovLiga(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GameRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Time)
	if l > 0 {
		n += 1 + l + sovLiga(uint64(l))
	}
	if m.Condtion {
		n += 2
	}
	if m.FirstTeamId != 0 {
		n += 1 + sovLiga(uint64(m.FirstTeamId))
	}
	if m.SecondTeamId != 0 {
		n += 1 + sovLiga(uint64(m.SecondTeamId))
	}
	if m.ResultFirstTeam != 0 {
		n += 1 + sovLiga(uint64(m.ResultFirstTeam))
	}
	if m.ResultSecondTeam != 0 {
		n += 1 + sovLiga(uint64(m.ResultSecondTeam))
	}
	if m.FirstTeamPoint != 0 {
		n += 1 + sovLiga(uint64(m.FirstTeamPoint))
	}
	if m.SecondTeamPoint != 0 {
		n += 1 + sovLiga(uint64(m.SecondTeamPoint))
	}
	if m.LigaId != 0 {
		n += 1 + sovLiga(uint64(m.LigaId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovLiga(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLiga(x uint64) (n int) {
	return sovLiga(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AllLigaRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiga
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AllLigaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AllLigaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLiga(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiga
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ligas) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiga
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ligas: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ligas: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ligas", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiga
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiga
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ligas = append(m.Ligas, &LigaResponse{})
			if err := m.Ligas[len(m.Ligas)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiga(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiga
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LigaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiga
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LigaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LigaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiga
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiga
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiga
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiga
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiga
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiga
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiga(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiga
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LigaRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiga
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LigaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LigaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiga
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiga
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiga(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiga
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiga
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLiga(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiga
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AllGameRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiga
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AllGameRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AllGameRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLiga(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiga
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Games) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiga
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Games: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Games: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Games", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiga
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiga
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Games = append(m.Games, &GameResponse{})
			if err := m.Games[len(m.Games)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiga(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiga
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiga
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiga
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiga
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Time = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Condtion", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Condtion = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstTeamId", wireType)
			}
			m.FirstTeamId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstTeamId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecondTeamId", wireType)
			}
			m.SecondTeamId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecondTeamId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultFirstTeam", wireType)
			}
			m.ResultFirstTeam = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResultFirstTeam |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultSecondTeam", wireType)
			}
			m.ResultSecondTeam = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResultSecondTeam |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstTeamPoint", wireType)
			}
			m.FirstTeamPoint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstTeamPoint |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecondTeamPoint", wireType)
			}
			m.SecondTeamPoint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecondTeamPoint |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LigaId", wireType)
			}
			m.LigaId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LigaId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiga
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiga
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiga
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiga
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiga(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiga
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GameRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiga
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GameRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GameRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiga
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiga
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Time = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Condtion", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Condtion = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstTeamId", wireType)
			}
			m.FirstTeamId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstTeamId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecondTeamId", wireType)
			}
			m.SecondTeamId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecondTeamId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultFirstTeam", wireType)
			}
			m.ResultFirstTeam = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResultFirstTeam |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultSecondTeam", wireType)
			}
			m.ResultSecondTeam = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResultSecondTeam |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstTeamPoint", wireType)
			}
			m.FirstTeamPoint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstTeamPoint |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecondTeamPoint", wireType)
			}
			m.SecondTeamPoint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecondTeamPoint |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LigaId", wireType)
			}
			m.LigaId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LigaId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLiga(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiga
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLiga(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLiga
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiga
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLiga
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLiga
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLiga
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLiga        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLiga          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLiga = fmt.Errorf("proto: unexpected end of group")
)
